const $=id=>document.getElementById(id);let selected=null,inputMode='upload';
const file=$('video'),preview=$('preview'),start=$('start');
const fallback=[['Zephyr','Bright'],['Puck','Upbeat'],['Charon','Informative'],['Kore','Firm'],['Fenrir','Excitable'],['Leda','Youthful'],['Orus','Firm'],['Aoede','Breezy'],['Callirrhoe','Easy-going'],['Autonoe','Bright'],['Enceladus','Breathy'],['Iapetus','Clear'],['Umbriel','Easy-going'],['Algieba','Smooth'],['Despina','Smooth'],['Erinome','Clear'],['Algenib','Gravelly'],['Rasalgethi','Informative'],['Laomedeia','Upbeat'],['Achernar','Soft'],['Alnilam','Firm'],['Schedar','Even'],['Gacrux','Mature'],['Pulcherrima','Forward'],['Achird','Friendly'],['Zubenelgenubi','Casual'],['Vindemiatrix','Gentle'],['Sadachbia','Lively'],['Sadaltager','Knowledgeable'],['Sulafat','Warm']];
function setHealth(d){const h=$('health');if(d.gemini_configured){h.textContent='● AI Ready';h.className='ready'}else{h.textContent='● Add GEMINI_API_KEY';h.className='warn'}}
async function loadHealth(){try{const r=await fetch('/api/health');setHealth(await r.json())}catch(e){$('health').textContent='● Server error';$('health').className='warn'}}
function fillVoices(list){const s=$('voice');s.innerHTML='';list.forEach(v=>{let o=document.createElement('option');o.value=v.id;o.textContent=`${v.name}${v.description?' — '+v.description:''}`;s.appendChild(o)});if([...s.options].some(o=>o.value==='Kore'))s.value='Kore';$('voiceCount').textContent=`${list.length} voices available`}
async function loadVoices(){try{let r=await fetch('/api/voices');let d=await r.json();fillVoices(d.voices||[])}catch(e){fillVoices(fallback.map(x=>({id:x[0],name:x[0],description:x[1]})))}}
function activateMode(mode){inputMode=mode;$('uploadTab').classList.toggle('active',mode==='upload');$('linkTab').classList.toggle('active',mode==='link');$('uploadPane').classList.toggle('hidden',mode!=='upload');$('linkPane').classList.toggle('hidden',mode!=='link');if(mode==='link'){selected=null;file.value=''}else{$('videoUrl').value=''};updateStart()}
function updateStart(){start.disabled=!(inputMode==='upload'?!!selected:$('videoUrl').value.trim().length>0)}
$('uploadTab').addEventListener('click',()=>activateMode('upload'));$('linkTab').addEventListener('click',()=>activateMode('link'));
file.addEventListener('change',()=>{selected=file.files[0];if(!selected)return;preview.src=URL.createObjectURL(selected);$('fileName').textContent=selected.name;$('previewWrap').classList.remove('hidden');updateStart()});
$('useLink').addEventListener('click',()=>{const u=$('videoUrl').value.trim();if(!u)return err('Video link ထည့်ပေးပါ။');$('previewWrap').classList.add('hidden');$('fileName').textContent=u;updateStart()});
$('videoUrl').addEventListener('input',updateStart);
$('voiceSearch').addEventListener('input',()=>{let q=$('voiceSearch').value.toLowerCase();[...$('voice').options].forEach(o=>o.hidden=!o.textContent.toLowerCase().includes(q))});
function err(m){$('error').textContent=m;$('error').classList.remove('hidden')}function prog(n,m){$('progress').classList.remove('hidden');$('bar').style.width=n+'%';$('percent').textContent=n+'%';$('status').textContent=m}
['brightness','contrast','saturation'].forEach(id=>{$(id).addEventListener('input',()=>{$(id+'Out').textContent=id==='brightness'?$(id).value:Number($(id).value).toFixed(2)})});
start.addEventListener('click',async()=>{if(inputMode==='upload'&&!selected)return;if(inputMode==='link'&&!$('videoUrl').value.trim())return;start.disabled=true;$('error').classList.add('hidden');$('result').classList.add('hidden');prog(5,inputMode==='link'?'Preparing video link…':'Uploading video…');let fd=new FormData();if(inputMode==='upload')fd.append('video',selected);else fd.append('video_url',$('videoUrl').value.trim());fd.append('voice',$('voice').value);fd.append('style',$('style').value);fd.append('custom_style',$('customStyle').value);fd.append('subtitle_mode',document.querySelector('input[name="subtitle"]:checked').value);fd.append('color_preset',$('colorPreset').value);fd.append('brightness',$('brightness').value);fd.append('contrast',$('contrast').value);fd.append('saturation',$('saturation').value);fd.append('subtitle_font_size',$('subtitleFont').value);fd.append('subtitle_scale_x',$('subtitleScaleX').value);fd.append('subtitle_scale_y',$('subtitleScaleY').value);fd.append('subtitle_x',$('subtitleX').value);fd.append('subtitle_y',$('subtitleY').value);fd.append('subtitle_alignment',$('subtitleAlignment').value);fd.append('subtitle_color',$('subtitleColor').value);fd.append('subtitle_outline_width',$('subtitleOutline').value);fd.append('subtitle_outline_color',$('subtitleOutlineColor').value);fd.append('subtitle_shadow',$('subtitleShadow').value);fd.append('subtitle_background',$('subtitleBackground').checked?'true':'false');fd.append('subtitle_background_color',$('subtitleBgColor').value);fd.append('subtitle_background_opacity',$('subtitleBgOpacity').value);fd.append('music_track',$('musicTrack').value);fd.append('music_volume',Number($('musicVolume').value)/100);fd.append('auto_thumbnail',$('autoThumbnail').checked?'true':'false');try{let r=await fetch('/api/process',{method:'POST',body:fd}),d=await r.json();if(!r.ok)throw Error(d.detail||'Video input failed');await poll(d.job_id)}catch(e){err(e.message);start.disabled=false}});
async function poll(id){while(true){let r=await fetch('/api/jobs/'+id),d=await r.json();if(!r.ok)throw Error(d.detail||'Job error');prog(d.progress||0,d.message||'Processing…');if(d.status==='done'){$('finalVideo').src=d.video_url;$('download').href=d.video_url;if(d.thumbnail_url){$('thumbnailImage').src=d.thumbnail_url;$('thumbnailDownload').href=d.thumbnail_url;$('thumbResult').classList.remove('hidden')}else{$('thumbResult').classList.add('hidden')}$('transcript').textContent=d.transcript||'';$('translation').textContent=d.translation||'';$('result').classList.remove('hidden');$('result').scrollIntoView({behavior:'smooth'});start.disabled=false;return}if(d.status==='error'){let msg=d.message||'Processing failed'; try{let dr=await fetch('/api/jobs/'+id+'/debug');let dd=await dr.json(); msg+='\n\nDebug files: '+(dd.files||[]).join(', ');}catch(_e){} throw Error(msg);}await new Promise(r=>setTimeout(r,2000))}}
const editorDefaults={x:50,y:88,font:52,sx:100,sy:100,align:2,color:'#FFFFFF',outlineColor:'#000000',outline:3,shadow:1,bg:true,bgColor:'#000000',bgOpacity:55};
function anchorTransform(a){const map={1:'translate(0,-100%)',2:'translate(-50%,-100%)',3:'translate(-100%,-100%)',4:'translate(0,-50%)',5:'translate(-50%,-50%)',6:'translate(-100%,-50%)',7:'translate(0,0)',8:'translate(-50%,0)',9:'translate(-100%,0)'};return map[Number(a)]||map[2]}
function hexRgb(hex){const h=hex.replace('#','');return `${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)}`}
function updateEditor(){const x=Number($('subtitleX').value),y=Number($('subtitleY').value),fs=Number($('subtitleFont').value),sx=Number($('subtitleScaleX').value),sy=Number($('subtitleScaleY').value),a=Number($('subtitleAlignment').value),tr=anchorTransform(a);const e=$('editorText');e.style.left=x+'%';e.style.top=y+'%';e.style.transform=tr+` scale(${sx/100},${sy/100})`;e.style.fontSize=Math.max(8,fs/2)+'px';e.style.color=$('subtitleColor').value;e.style.border=`${Math.max(0,Number($('subtitleOutline').value)/2)}px solid ${$('subtitleOutlineColor').value}`;e.style.textShadow=`0 ${Number($('subtitleShadow').value)}px ${Math.max(1,Number($('subtitleShadow').value)*2)}px #000`;e.style.background=$('subtitleBackground').checked?`rgba(${hexRgb($('subtitleBgColor').value)},${Number($('subtitleBgOpacity').value)/100})`:'transparent';$('subtitleXOut').textContent=x+'%';$('subtitleYOut').textContent=y+'%';$('subtitleFontOut').textContent=fs;$('subtitleScaleXOut').textContent=sx+'%';$('subtitleScaleYOut').textContent=sy+'%';$('subtitleOutlineOut').textContent=$('subtitleOutline').value;$('subtitleShadowOut').textContent=$('subtitleShadow').value;$('subtitleBgOpacityOut').textContent=$('subtitleBgOpacity').value+'%';const pe=$('subtitlePreview');pe.style.left=x+'%';pe.style.top=y+'%';pe.style.transform=tr+` scale(${sx/100},${sy/100})`;pe.style.fontSize=Math.max(8,fs/2)+'px';pe.style.color=$('subtitleColor').value;pe.style.textShadow=`0 ${Number($('subtitleShadow').value)}px ${Math.max(1,Number($('subtitleShadow').value)*2)}px #000`;pe.style.background=$('subtitleBackground').checked?`rgba(${hexRgb($('subtitleBgColor').value)},${Number($('subtitleBgOpacity').value)/100})`:'transparent'}
function setEditor(d){$('subtitleX').value=d.x;$('subtitleY').value=d.y;$('subtitleFont').value=d.font;$('subtitleScaleX').value=d.sx;$('subtitleScaleY').value=d.sy;$('subtitleAlignment').value=d.align;$('subtitleColor').value=d.color;$('subtitleOutlineColor').value=d.outlineColor;$('subtitleOutline').value=d.outline;$('subtitleShadow').value=d.shadow;$('subtitleBackground').checked=d.bg;$('subtitleBgColor').value=d.bgColor;$('subtitleBgOpacity').value=d.bgOpacity;updateEditor()}
['subtitleX','subtitleY','subtitleFont','subtitleScaleX','subtitleScaleY','subtitleAlignment','subtitleColor','subtitleOutlineColor','subtitleOutline','subtitleShadow','subtitleBackground','subtitleBgColor','subtitleBgOpacity'].forEach(id=>$(id).addEventListener('input',updateEditor));
['subtitleAlignment','subtitleColor','subtitleOutlineColor','subtitleBackground','subtitleBgColor'].forEach(id=>$(id).addEventListener('change',updateEditor));
$('subtitleReset').addEventListener('click',()=>setEditor(editorDefaults));
let dragging=false;const stage=$('editorStage'),et=$('editorText');function dragMove(ev){if(!dragging)return;const r=stage.getBoundingClientRect();let x=(ev.clientX-r.left)/r.width*100,y=(ev.clientY-r.top)/r.height*100;x=Math.max(0,Math.min(100,x));y=Math.max(0,Math.min(100,y));$('subtitleX').value=x.toFixed(1);$('subtitleY').value=y.toFixed(1);updateEditor()}et.addEventListener('pointerdown',ev=>{dragging=true;et.setPointerCapture(ev.pointerId);ev.preventDefault()});et.addEventListener('pointermove',dragMove);et.addEventListener('pointerup',()=>dragging=false);et.addEventListener('pointercancel',()=>dragging=false);setEditor(editorDefaults);
loadHealth();loadVoices();
$('musicVolume').addEventListener('input',()=>{$('musicVolumeOut').textContent=$('musicVolume').value+'%' });
